Feature/nlp counter
imgcook/datacook pull request #13
Opened 2020-11-27 16:33 UTC by steveoni

This pull request implements the python `collections.Counter` like, containing the use-case as shown below.

```js
const counter = new Counter({ 'good': 2, 'bad': 2, 'neutral': 3 });
counter.update({'good':4,'bad':2,'food':1})

counter.mostCommon(2) // [ ['good', 6], ['bad', 4] ]

counter.element // [ ['good', 6], ['bad', 4], ['neutral', 3], ['food', 1]]
counter.wordCount // {good': 6, 'bad': 4, 'neutral': 3, 'food':1}
```

2020-11-28 04:26 UTC, yorkie requested changes

2020-11-28 04:26 UTC, yorkie commented on src/text/counter.ts
> +   * Initializer COunter class
```suggestion
   * Initializer Counter class
```

2020-11-28 04:26 UTC, yorkie commented on src/text/counter.ts
> +  constructor (textInput: CounterType){
```suggestion
  constructor (textInput: CounterType) {
```

2020-11-28 04:26 UTC, yorkie commented on src/text/counter.ts
> +    if (Array.isArray(textInput)){
Ditto

2020-11-28 04:26 UTC, yorkie commented on src/text/counter.ts
> +      let toArray = textInput.split('');
```suggestion
      const toArray = textInput.split("");
```

2020-11-28 04:26 UTC, yorkie commented on src/text/counter.ts
> +    for (const key in updateCounter.wordCount){
```suggestion
    for (const key in updateCounter.wordCount) {
```

2020-11-28 04:27 UTC, yorkie commented
@steveoni @risenW Shall we have set up a coding style check, though?

2020-12-01 18:23 UTC, steveoni commented
> @steveoni @risenW Shall we have set up a coding style check, though?

Yeah. I'm using Prettier plugins with the Eslint configs, I thought that will handle this style issue. I will check it out and make another commit

2020-12-07 12:20 UTC, yorkie approved these changes

2020-12-07 12:48 UTC, FeelyChau submitted a review, later dismissed

2020-12-07 12:48 UTC, FeelyChau commented on test/text/counter.ts
> +});
missing EOF :)

2020-12-07 12:48 UTC, FeelyChau commented on src/text/counter.ts
> +
Ditto.

2020-12-07 12:48 UTC, FeelyChau commented on src/text/counter.ts
> +
Unnecessary blank line.

2020-12-07 15:22 UTC, yorkie commented
@FeelyChau your reviews are style nits from Pipcook, but I think datacook owns itself, it depends on datacook team @risenW @steveoni and @WenheLI :)

2020-12-07 15:48 UTC, FeelyChau commented
> @FeelyChau your reviews are style nits from Pipcook, but I think datacook owns itself, it depends on datacook team @risenW @steveoni and @WenheLI :)

Yeah, you are right. Maybe I should enable the lint in another PR if you wish.

2020-12-07 15:55 UTC, yorkie commented
@FeelyChau Ok, that's great for the community, and I dismissed yours because they are invalid to this PR :)

2020-12-07 20:17 UTC, merged