feat: add beta distribution
imgcook/datacook pull request #26
Opened 2021-01-21 08:46 UTC by WenheLI

2021-01-22 02:23 UTC, WenheLI commented
We should consider overflow & underflow for extreme value.

2021-01-25 15:47 UTC, yorkie commented
How about adding some unit tests for this function?

2021-01-26 02:48 UTC, WenheLI commented
@yorkie - Testing for random functions is kinda tricky. I am trying to find a way of testing.

2021-01-26 04:03 UTC, risenW requested changes

2021-01-26 04:03 UTC, risenW commented on test/node/rand/index.ts
> +  it('should return tensor wiht one value', () => {
A little typo here:` it('should return tensor wiht one value')...` should be `it('should return tensor with one value'`

2021-01-26 04:03 UTC, risenW commented on test/node/rand/index.ts
> +  it('should return tensor wiht multi value', () => {
Same typo mistake here

2021-01-26 04:04 UTC, risenW commented
> @yorkie - Testing for random functions is kinda tricky. I am trying to find a way of testing.

True, except you find a way to seed the function

2021-01-26 05:27 UTC, yorkie commented on package.json
> +    "compile": "make",
```suggestion
    "build:wasm": "make",
```

2021-01-26 05:28 UTC, yorkie commented on src/rand/beta.ts
> +  setParam(a: number, b: number): void;
Add some description?

2021-02-04 03:23 UTC, WenheLI commented
@yorkie gentle ping

2021-02-04 05:29 UTC, yorkie approved these changes

2021-02-04 07:48 UTC, WenheLI commented
@risenW - Gentle ping

2021-02-04 14:58 UTC, risenW approved these changes

2021-02-04 14:58 UTC, risenW commented
@WenheLI looks good

2021-02-04 15:07 UTC, merged