Linear regression and logistic regression
imgcook/datacook pull request #65
Opened 2021-09-06 07:52 UTC by sugarspectre

2021-09-07 04:47 UTC, FeelyChau requested changes

2021-09-07 04:47 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +   optimizerType?: OptimizerType,
indent

2021-09-07 04:47 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +   optimizerProps?: OptimizerProps
ditto

2021-09-10 07:23 UTC, yorkie commented on browser-examples/logistic-regression.html
> +<html>
examples/browser or examples/web

2021-09-10 07:28 UTC, FeelyChau requested changes

2021-09-10 07:28 UTC, FeelyChau commented on package.json
> +    "webpack-visualizer-plugin": "^0.1.11"
Move to `devDependencies'.

2021-09-10 07:28 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +    if (values.dtype == 'int32' || values.dtype == 'float32') {
```suggestion
    if (values.dtype === 'int32' || values.dtype === 'float32') {
```

2021-09-10 07:28 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +    } else if (values.dtype == 'bool') {
```suggestion
    } else if (values.dtype === 'bool') {
```

2021-09-10 07:28 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +    const shapeCorrect = codeSize > 1 ? checkShape(x, [ -1, codeSize ]) : (checkShape(x, [ -1 ]) || (checkShape(x, [ -1, 1 ])));
```suggestion
    const shapeCorrect = codeSize > 1 ? checkShape(x, [ -1, codeSize ]) : (checkShape(x, [ -1 ]) || checkShape(x, [ -1, 1 ]));
```

2021-09-10 07:28 UTC, FeelyChau commented on src/utils/optimizer-types.ts
> +      throw new TypeError('Illegal properties to init optimizer');
The non-null assert can be moved to outside of the `switch`.

2021-09-10 07:28 UTC, FeelyChau commented on webpack.config.js
> +      //index: './dist/index.js',
should enable the index entry.

2021-09-10 07:28 UTC, yorkie commented on package.json
> +    "webpack-visualizer-plugin": "^0.1.11"
This should not be in dependencies.

2021-09-10 07:28 UTC, yorkie commented on package.json
> +    "babel-loader": "^8.2.2",
Ditto

2021-09-10 07:29 UTC, yorkie commented on package.json
> +    "@babel/preset-env": "^7.15.4",
Ditto.

2021-09-10 12:52 UTC, FeelyChau requested changes

2021-09-10 12:52 UTC, FeelyChau commented on src/model/linear-model/logistic-regression-predictor.ts
> +    if (modelParams.name !== 'LogisticRegression'){
```suggestion
    if (modelParams.name !== 'LogisticRegression') {
```

2021-09-10 12:52 UTC, FeelyChau commented on src/model/linear-model/logistic-regression-predictor.ts
> +    classes && this.initClasses(classes, 'binary-only');
```suggestion
    if (classes) {
        this.initClasses(classes, 'binary-only');
    }
```

2021-09-13 03:19 UTC, FeelyChau requested changes

2021-09-13 03:19 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +    //this.optimizer = params.optimizer && params.optimizer instanceof Optimizer ? params.optimizer : train.adam(0.1);
Remove unused lines.

2021-09-13 03:19 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +  constructor(params: LogisticRegressionParams = {
If pass `{ c: 1 }`, the penalty will be set to `undefined`, is this expected?

2021-09-13 03:19 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +      kernelRegularizer: penalty == 'l2' ? regularizers.l2({ l2: c }) : penalty == 'l1' ? regularizers.l1({ l1: c }) : null }));
```suggestion
      kernelRegularizer: penalty === 'l2' ? regularizers.l2({ l2: c }) : penalty === 'l1' ? regularizers.l1({ l1: c }) : null }));
```

2021-09-13 03:19 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +    modelWeights.length && model.setWeights(modelWeights);
```suggestion
  if (modelWeights.length > 0) {
    model.setWeights(modelWeights);
  }
```

2021-09-13 03:19 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +      if (nFeature != this.featureSize) {
```suggestion
      if (nFeature !== this.featureSize) {
```

2021-09-13 03:19 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +  public getCoef(): { 'coefficients': Tensor, 'intercept': Tensor} {
```suggestion
  public getCoef(): { coefficients: Tensor, intercept: Tensor } {
```

2021-09-13 04:51 UTC, FeelyChau commented
LGTM.

2021-09-13 04:52 UTC, FeelyChau approved these changes

2021-09-13 05:21 UTC, merged