Beta Merge to Main
imgcook/datacook pull request #66
Opened 2021-09-13 07:36 UTC by sugarspectre

2021-09-14 05:12 UTC, yorkie requested changes

2021-09-14 05:12 UTC, yorkie commented on package.json
> +    "webpack-visualizer-plugin": "^0.1.11",
This is useless.

2021-09-14 05:12 UTC, yorkie commented on src/linalg/eigen.ts
> +export const solveEigenValues = async(matrix: Tensor, tol = 1e-4, maxIter = 200): Promise<Tensor> => {
```suggestion
export const solveEigenValues = async (matrix: Tensor, tol = 1e-4, maxIter = 200): Promise<Tensor> => {
```

2021-09-14 05:12 UTC, yorkie commented on src/linalg/eigen.ts
> +export const eigenBackSolve = async(matrix: Tensor, eigenValue: number, tol = 1e-4, maxIter = 200): Promise<Tensor> => {
```suggestion
export const eigenBackSolve = async (matrix: Tensor, eigenValue: number, tol = 1e-4, maxIter = 200): Promise<Tensor> => {
```
Ditto.

2021-09-14 05:12 UTC, yorkie commented on src/linalg/eigen.ts
> +export const eigenSolve = async(matrix: Tensor, tol = 1e-4, maxIter = 200): Promise<[Tensor, Tensor]> => {
Ditto

2021-09-14 05:12 UTC, yorkie commented on src/linalg/inverse.ts
> +export const inverse = async(matrix: Tensor): Promise<Tensor> => {
Ditto.

2021-09-14 06:50 UTC, yorkie requested changes

2021-09-14 06:50 UTC, yorkie commented on src/linalg/eigen.ts
> + * Compute the eigenvalues and eigenvectors of a matrix M.
Where is the matrix M?

2021-09-14 06:50 UTC, yorkie commented on src/linalg/inverse.ts
> +  if (isSquareMatrix) {
```suggestion
  if (isSquareMatrix(matrix)) {
```

2021-09-14 06:50 UTC, yorkie commented on src/linalg/inverse.ts
> +  }
```js
    if (invertable) {
      const inverseEigenValues = divNoNan(1, eigenValues);
      return matMul(matMul(eigenVectors, diag(inverseEigenValues)), transpose(eigenVectors));
    }
  }
  throw new TypeError('Singular matrix error');
```

2021-09-14 06:50 UTC, yorkie commented on src/linalg/linsolve.ts
> +export const linSolveFromQR = async(q: Tensor, r: Tensor, v: Tensor): Promise<Tensor> => {
```suggestion
export const linSolveFromQR = async (q: Tensor, r: Tensor, v: Tensor): Promise<Tensor> => {
```

2021-09-14 06:50 UTC, yorkie commented on src/linalg/linsolve.ts
> +export const linSolveQR = async(matrix: Tensor, v: Tensor): Promise<Tensor> => {
Ditto

2021-09-14 06:50 UTC, yorkie commented on src/linalg/linsolve.ts
> +  return solution;
```suggestion
  return await linSolveFromQR(q, r, v);
```

2021-09-14 06:50 UTC, yorkie commented on src/linalg/svd.ts
> +export const svd = async(matrix: Tensor, tol = 1e-4, maxIter = 200): Promise<[ Tensor, Tensor, Tensor ]> => {
Ditto.

2021-09-14 06:52 UTC, yorkie commented on src/model/base.ts
> +    return yOnehot;
```suggestion
    return await this.classOneHotEncoder.encode(y);
```

2021-09-14 06:52 UTC, yorkie commented on src/model/base.ts
> +    return nClass == 2;
```suggestion
    return this.classes().shape[0] == 2;
```

2021-09-14 06:52 UTC, yorkie commented on src/model/base.ts
> +    return predClass;
```suggestion
    return await this.classOneHotEncoder.decode(score);
```

2021-09-14 06:56 UTC, FeelyChau requested changes

2021-09-14 06:56 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +  public getCoef(): { 'coefficients': Tensor, 'intercept': Tensor} {
Why use single quotes in the field name?

2021-09-14 06:56 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +    if (optimizerType as OptimizerType && optimizerProps as OptimizerProps) {
If you want to make a type judgment, you need to use the [`is` operator](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates)

2021-09-14 06:56 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +    }
```suggestion
    if (!this.model) {
      if (!this.classes() || !this.classes().shape[0]) await this.initClasses(y, 'binary-only');
      const outputShape = this.isBinaryClassification() ? 1 : this.classes().shape[0];
      this.initModel(nFeature, outputShape, this.fitIntercept);
      this.featureSize = nFeature;
      this.outputSize = outputShape;
    } else if (nFeature !== this.featureSize) {
      throw new Error('feature size does not match previous training set');
    }
```

2021-09-14 06:56 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +    this.fitIntercept = (fitIntercept as boolean);
```suggestion
    this.fitIntercept = !!fitIntercept;
```

2021-09-14 06:56 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +      fitIntercept: await this.fitIntercept,
What is this `await` for?

2021-09-14 06:56 UTC, yorkie commented on src/model/linear-model/linear-regression.ts
> +        throw new Error('feature size does not match previous training set');
```suggestion
        throw new TypeError('feature size does not match previous training set');
```

2021-09-14 06:56 UTC, yorkie commented on src/model/linear-model/linear-regression.ts
> +      if (nFeature != this.featureSize) {
```suggestion
      if (nFeature !== this.featureSize) {
```

2021-09-14 06:59 UTC, yorkie commented on src/model/linear-model/linear-regression.ts
> +    return weights;
```suggestion
    return await Promise.all(this.model.getWeights().map(async w => awit w.array());
```

2021-09-14 07:00 UTC, FeelyChau commented on src/model/linear-model/linear-regression.ts
> +    this.fitIntercept = (fitIntercept as boolean);
`as` operator can not do the type conversion for you, it's just a compile-time type conversion.
After building, the code will  be:
```js
this.fitIntercept = fitIntercept;
```

2021-09-14 07:02 UTC, yorkie commented on src/model/linear-model/linear-regression.ts
> +      throw new RangeError(`${modelParams.name} is not Linear Regression`);
Why a RangeError?

2021-09-14 07:02 UTC, yorkie commented on src/model/linear-model/linear-regression.ts
> +    if (modelParams.name !== 'LinearRegression'){
```suggestion
    if (modelParams.name !== 'LinearRegression') {
```

2021-09-14 07:05 UTC, yorkie commented on src/model/linear-model/logistic-regression-predictor.ts
> +    return predClasses;
```suggestion
    return await this.getPredClass(scores);
```

2021-09-14 07:05 UTC, yorkie commented on src/utils/optimizer-types.ts
> +}
```suggestion
};
```

2021-09-14 07:06 UTC, yorkie commented on src/utils/optimizer-types.ts
> +}
Ditto.

2021-09-14 07:07 UTC, yorkie commented on src/utils/optimizer-types.ts
> +function isAdaMaxProps(arg:any): arg is AdamProps {
```suggestion
function isAdaMaxProps(arg: any): arg is AdamProps {
```

2021-09-14 07:08 UTC, yorkie commented on src/utils/optimizer-types.ts
> +    throw new TypeError('Illegal optimizer type');
```suggestion
    throw new TypeError('Illegal optimizer type: ' + optimizerTypes);
```

2021-09-14 07:08 UTC, yorkie commented on src/utils/optimizer-types.ts
> +export const getOptimizer = (optimizerTypes: OptimizerType, optimizerProps: OptimizerProps): Optimizer => {
`optimizerTypes` => optimizerType, it represents a type.

2021-09-14 07:10 UTC, yorkie commented on web-examples/logistic-regression.html
> +<script>
The above indentions are wrong.

2021-09-14 07:11 UTC, yorkie commented on webpack.config.js
> +const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
```suggestion
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');
```

2021-09-14 07:11 UTC, yorkie commented on webpack.config.js
> +      // TODO: recover index entry
How about other entries?

2021-09-14 07:13 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +    if (predY instanceof Tensor){
```suggestion
    if (predY instanceof Tensor) {
```

2021-09-14 07:13 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +      const j = Math.floor(i%(batchSize));
```suggestion
      const j = Math.floor(i % (batchSize));
```

2021-09-14 07:14 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +      console.log('accuracy: ', acc);
```suggestion
      console.log('accuracy:', acc);
```
Console will append a space automatically.

2021-09-14 07:15 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +    if (predY instanceof Tensor){
```suggestion
    if (predY instanceof Tensor) {
```

2021-09-14 07:16 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +      console.log('accuracy: ', acc);
```suggestion
      console.log('accuracy:', acc);
```

2021-09-14 07:16 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +    if (predY instanceof Tensor){
```suggestion
    if (predY instanceof Tensor) {
```

2021-09-14 07:16 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +      console.log('accuracy: ', acc);
```suggestion
      console.log('accuracy:', acc);
```

2021-09-14 07:16 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +    if (predY instanceof Tensor){
```suggestion
    if (predY instanceof Tensor) {
```

2021-09-14 07:16 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +      console.log('accuracy: ', acc);
```suggestion
      console.log('accuracy:', acc);
```

2021-09-14 07:17 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +    if (predY instanceof Tensor){
```suggestion
    if (predY instanceof Tensor) {
```

2021-09-14 07:17 UTC, yorkie commented on test/node/model/logistic-regression.ts
> +      console.log('accuracy: ', acc);
```suggestion
      console.log('accuracy:', acc);
```

2021-09-14 08:05 UTC, FeelyChau commented on src/model/base.ts
> +    return nClass == 2;
`===` is better.

2021-09-15 03:49 UTC, FeelyChau requested changes

2021-09-15 03:49 UTC, FeelyChau commented on src/linalg/utils.ts
> + * Check that if a tensor a square matrix
```suggestion
 * Check that if a tensor is a square matrix
```

2021-09-15 03:49 UTC, FeelyChau commented on src/linalg/utils.ts
> +  return false;
```suggestion
  return checkDimension(matrix, 2) && matrix.shape[0] === matrix.shape[1];
```

2021-09-15 03:49 UTC, FeelyChau commented on src/linalg/utils.ts
> +  return true;
```suggestion
  }
  for (let i = 0; i < shape1.length; i++) {
    if (shape1[i] !== shape2[i]) {
      return false;
    }
  }
  return true;
```
OR:
```suggestion
  } else {
    for (let i = 0; i < shape1.length; i++) {
      if (shape1[i] !== shape2[i]) {
        return false;
      }
    }
    return true;
  }
```

2021-09-15 03:49 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +      return await this.getPredClass(scores);
```suggestion
      return this.getPredClass(scores);
```

2021-09-15 03:49 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +      return await this.getPredClass(stack(scores));
```suggestion
      return this.getPredClass(stack(scores));
```

2021-09-15 03:49 UTC, FeelyChau commented on src/model/linear-model/logistic-regression.ts
> +      fitIntercept: await this.fitIntercept,
```suggestion
      fitIntercept: this.fitIntercept,
```

2021-09-15 03:49 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +    }
```suggestion
    }
    const xTensor = checkArray(x, 'any', 1);
    const xData = await xTensor.dataSync();
    const nCate = this.categories.shape[0];
    const xInd = xData.map((d: number|string) => this.cateMap[d]);
    if (this.drop === 'binary-only' && nCate === 2) {
      return tensor(xInd);
    } else if (this.drop === 'first') {
      return oneHot(cast(sub(tensor(xInd), 1), 'int32'), nCate - 1);
    } else {
      return oneHot(cast(tensor(xInd), 'int32'), nCate);
    }
```

2021-09-15 03:49 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +        return cateTensors.push(slice(this.categories, ind, 1));
```suggestion
        cateTensors.push(slice(this.categories, ind, 1));
```

2021-09-15 03:49 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +        return cateTensors.push(slice(this.categories, ind + 1, 1));
```suggestion
        if (Number(slice(x, [ i, ind ], [ 1, 1 ]).dataSync()) === 0) {
         cateTensors.push(slice(this.categories, 0, 1));
        } else {
         cateTensors.push(slice(this.categories, ind + 1, 1));
        }
```

2021-09-15 03:49 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +        return cateTensors.push(slice(this.categories, ind, 1));
```suggestion
       cateTensors.push(slice(this.categories, ind, 1));
```

2021-09-15 03:49 UTC, FeelyChau commented on src/preprocess/encoder.ts
> +          throw Error('Index out of range');
```suggestion
          throw RangeError('Index out of range');
```

2021-09-15 03:49 UTC, FeelyChau commented on src/utils/optimizer-types.ts
> +  return false;
```suggestion
  return arg?.learningRate > 0;
```

2021-09-15 03:49 UTC, FeelyChau commented on src/utils/optimizer-types.ts
> +  return false;
```suggestion
  return arg?.learningRate > 0 && arg?.momentum > 0;
```

2021-09-15 03:49 UTC, FeelyChau commented on src/utils/optimizer-types.ts
> +  return false;
```suggestion
  return arg?.learningRate > 0 && arg?.initialAccumulatorValue > 0;
```

2021-09-15 03:49 UTC, FeelyChau commented on src/utils/optimizer-types.ts
> +  return false;
```suggestion
  return arg?.learningRate > 0;
```

2021-09-15 03:49 UTC, FeelyChau commented on src/utils/optimizer-types.ts
> +};
```suggestion
const optimizerTypeAssertMap = {
  sgd: isSGDProps,
  momentum: isMomentumProps,
  adagrad: isAdagradProps,
  adam: isAdamProps,
  adamax: isAdaMaxProps,
  rmsprop: isRMSPropProps
};

/**
 * Create optimizer depending on given type and props
 * @param optimizerType optimizer type
 * @param optimizerProps optimizer properties
 */
export const getOptimizer = (optimizerType: OptimizerType, optimizerProps: OptimizerProps): Optimizer => {
  const typeCheck = optimizerTypeAssertMap[optimizerType];
  if (typeCheck && !typeCheck(optimizerProps)) {
    throw new TypeError('Illegal properties to init optimizer');
  }
  switch (optimizerType) {
  case 'sgd':
    return train.sgd((optimizerProps as SGDProps).learningRate);
  case 'momentum':
    const { learningRate, momentum, useNesterov } = optimizerProps as MomentumProps;
    return train.momentum(learningRate, momentum, useNesterov);
  case 'adagrad':
    const { learningRate, initialAccumulatorValue } = optimizerProps as AdagradProps;
    return train.adagrad(learningRate, initialAccumulatorValue);
  case 'adadelta':
    const { learningRate, rho, epsilon } = optimizerProps as AdadeltaProps;
    return train.adadelta(learningRate, rho, epsilon);
  case 'adam': 
    const { learningRate, beta1, beta2, epsilon } = optimizerProps as AdamProps;
    return train.adam(learningRate, beta1, beta2, epsilon);
  case 'adamax':
    const { learningRate, beta1, beta2, epsilon, decay } = optimizerProps as AdamaxProps;
    return train.adamax(learningRate, beta1, beta2, epsilon, decay);
  case 'rmsprop':
    const { learningRate, decay, momentum, epsilon, centered } = optimizerProps as RMSPropProps;
    return train.rmsprop(learningRate, decay, momentum, epsilon, centered);
  default:
    throw new TypeError('Illegal optimizer type: ' + optimizerType);
  }
};
```

2021-09-15 07:43 UTC, FeelyChau approved these changes
LGTM.

2021-09-15 11:14 UTC, yorkie approved these changes

2021-09-16 07:09 UTC, merged