model clean method
imgcook/datacook pull request #77
Opened 2021-11-09 12:08 UTC by jan-www

Provide model clean method and parameter reset method for tensor memory release

2021-11-10 05:42 UTC, yorkie requested changes

2021-11-10 05:42 UTC, yorkie commented on src/model/base.ts
> +   * @param x Input feature of shape (nSample, nFeatures).
```suggestion
   * @param input feature of shape (nSample, nFeatures).
```

In tsdoc, we don't need to specify the variable name.

2021-11-10 05:42 UTC, yorkie commented on src/model/base.ts
> +   * @param reset if true, the `nFeatures` attribute is set to `x.shape[1]`.
```suggestion
   * @param if true, the `nFeatures` attribute is set to `x.shape[1]`.
```
Ditto.

2021-11-10 05:42 UTC, yorkie commented on src/model/base.ts
> +      throw new TypeError('Input should be 2D tensor');
```suggestion
      throw new TypeError('input should be 2D tensor');
```
I just found other messages are in lower-case for the first char.

2021-11-10 05:42 UTC, yorkie commented on src/model/base.ts
> +  public cleanAndSetParam(paramKey: Extract<keyof this, string>, val: any): void {
See GitHub Actions' comment.

2021-11-10 05:42 UTC, yorkie commented on test/node/model/base.ts
> +import 'mocha';
Is this required?

2021-11-10 05:42 UTC, yorkie commented on test/node/model/base.ts
> +  public c: number;
The above 2 members are useless.

2021-11-10 06:24 UTC, jan-www commented on test/node/model/base.ts
> +import 'mocha';
what do you mean?

2021-11-10 08:23 UTC, yorkie commented on test/node/model/base.ts
> +import 'mocha';
This line might be removed.

2021-11-10 13:05 UTC, yorkie approved these changes

2021-11-10 13:11 UTC, FeelyChau requested changes

2021-11-10 13:11 UTC, FeelyChau commented on src/model/base.ts
> +      throw new TypeError('Input should be 2D tensor');
Is it better to use type Tensor2d?

2021-11-10 13:14 UTC, FeelyChau requested changes

2021-11-10 13:14 UTC, FeelyChau commented on src/model/base.ts
> +   * @returns tensor of input data
Missing parameter `reset`.

2021-11-15 05:02 UTC, yorkie approved these changes
LGTM

2021-11-16 12:35 UTC, merged